### ISSUE TITLE
[1.18.2] Wild Corn plant not dropping seeds

### ISSUE THREAD

**Issue by ffuentesm** [Nyancatpig/Cultural-Delights-1.18.2#1]
Ver: culturaldelights-1.18.2-0.10.1.jar, FarmersDelight-1.18.2-1.1.0.jar
Forge: 40.1.19

When breaking the wild corn pant, there are no drops of seed.

**Comment by winnetrie83** [comment]
@ffuentesm You are supposed to plant the kernels. There are no seeds for corn.

**Comment by MarioSMB** [comment]
This is a valid issue; when you break wild corn it is dropping Wheat Seeds. The only way to obtain them currently is by shearing the wild corn and chopping it with a knife at a cutting board.

**Comment by Nyancatpig** [comment]
breaking wild corn has a chance to drop nothing, wheat seeds, and corn kernels
this is entirely intentional, but may be changed in the future

**Comment by MarioSMB** [comment]
It is rather unintuitive as it is (for both players and in the sense that it *looks* like a bug) and makes it difficult to obtain corn while not matching the behaviour of any of the other crops, I would encourage some changes to its behaviour so as to not cause confusion and frustration.
