### ISSUE TITLE
Cultural Delights disables vanilla recipes

### ISSUE THREAD

**Issue by MarioSMB** [Nyancatpig/Cultural-Delights-1.18.2#15]
The vanilla recipes for beetroot soup, bread, mushroom stew and rabbit stew are disabled by Cultural Delights.  
This unexpected change can negatively impact Minecraft gameplay as some of these dishes are the only way to refill hunger in some situations (such as mushrooms for stew in the Nether), along with triggering recipe errors in the log.

**Comment by Nyancatpig** [comment]
These changes were made as their old recipes do not make sense when Farmer’s Delight is installed, although the bread recipe should not have been removed
This may be added to a config in the future

**Comment by spiderman7801** [comment]
Hi @MarioSMB just seeing this now and I'm having the same issue with many errors on my server log. How did you solve this issue?

**Comment by MarioSMB** [comment]
@Nyancatpig With all due respect this change does not fit into an addon of Farmer's Delight and should be presented to the Farmer's Delight developers themselves, as otherwise those who install addons for FD will be caught off guard by these recipes randomly being disabled - not to mention the errors in the console!

Would you please consider re-opening this if not for the parts of it that are planned to be resolved?
I don't mind submitting a pull request for it if so desired.

**Comment by Aceplante** [comment]
What are you talking about? If you mean bread now being made from dough, which now requires an egg, that is a good thing and makes far more sense. Also you can use the dough to make dumplings. The three soups you mentioned though seem to work fine for me. In the cooking pot i mean. I dont know if they can still be crafted or not, but I understand why it would not be, like literally every other soup in this mod.

**Comment by MarioSMB** [comment]
Farmer's Delight does not disable the vanilla recipes, why should Cultural Delights (an addon for Farmer's Delight)?  
- There are errors in the console from recipes being removed incorrectly
- Nether survival is negatively impacted (mushroom stew is one of the only food sources readily available)

This is an addon, not a regular mod, disabling things Farmer's Delight is otherwise fine with can be considered intrusive.  
For example, if you install a mod that adds new zombie types but doesn't mention that it also disables creepers, you would not be expecting that, it would be an intrusive design choice that negatively affects your gameplay.  

If you don't agree with vanilla soup recipes being available in Farmer's Delight, make an issue on the Farmer's Delight page, don't change it in a random addon among many that people are playing Farmer's Delight with.
