### ISSUE TITLE
Grapes can't be right-click harvested with Quark and grape seeds can't be composted

### ISSUE THREAD

**Issue by DeadlyAccurate** [Nyancatpig/Cultural-Delights-1.18.2#19]
I can't use Quark's right-click Simple Harvest to harvest grapes, and I can't compost grape seeds in the vanilla composter. Also, less relevant but worth mentioning is that when punching a grape plant, I only ever get a single seed back, so I have to find all my grape seeds in the wild. Corn and eggplants are working fine; it's only grapes I'm having a problem with. 

1.18.2
Forge 40.1.80
culturaldelights-1.18.2-0.14.jar

**Comment by Nyancatpig** [comment]
Cultral Delights doesn’t add Grapes
and I don’t know any FD addons that do
🤔

**Comment by DeadlyAccurate** [comment]
Dang, my bad. It was Italian's Delight that adds them. Sorry about that.
