### ISSUE TITLE
Cant Get Squid Ink sac in culturaldelights-1.18.2-0.11

### ISSUE THREAD

**Issue by IchigoGames** [Nyancatpig/Cultural-Delights-1.18.2#2]
Minecraft 1.18.2
Forge Version 40.1.20
culturaldelights-1.18.2-0.11

Issue

New Squid meat replace ink sac drop your unable to get ink sec after updating to culturaldelights-1.18.2-0.11

Tested multiplayer and singplayer

**Comment by Nyancatpig** [comment]
you should be able to get inc sacs by cutting the squid meat on a cutting board

**Comment by IchigoGames** [comment]
oh then there needs to be some way to tell the players that i thought it would work like most mods that add squid meat and make it a extra drop not a replacement also it does not show that in rei but that may be due to me using the less popular option cant use jei due to a mod not working well with it.
