### ISSUE TITLE
[1.18.2] Hardcoded drops for crops

### ISSUE THREAD

**Issue by Sandriell** [Nyancatpig/Cultural-Delights-1.18.2#22]
Drops from all crops, both wild and farmed, are hardcoded rather than using the loot tables.

**Comment by Nyancatpig** [comment]
They aren't?
What brought you to that conclusion?

**Comment by Sandriell** [comment]
**Edit to add, when I was going back to verify my changes indeed did work again using the /loot command I noticed I had two listing for everything. The difference between a "block" and "blocks" folder.**

**My apologies, it is indeed working fine.**

Changing the loot_tables using a datapack has had no effect on the dropped items from either the wild or farmed versions of the crops. I have verified that my loot tables have been changed correctly using the /loot command which does drop the correct items.
