### ISSUE TITLE
MC 1.18.2 Advancement bug (minor)

### ISSUE THREAD

**Issue by winnetrie83** [Nyancatpig/Cultural-Delights-1.18.2#3]
MC version : 1.18.2
Forge version: 40.1.20
culturaldelights-1.18.2-0.11.jar

Joining a world for the first time rewards you the advancement:
"Funniest thing I've ever seen!"

**Comment by Water-Cat1** [comment]
its a syntax error on the advancement causing it to skip the needed requirement. Have attached a fixed pickle advancement for either use in the mod, or as a datapack (just change the extension to .json)
[pickle.txt](https://github.com/Nyancatpig/Cultural-Delights-1.18.2/files/8885491/pickle.txt)
.

**Comment by brdle** [comment]
I've PR'd a fix with #9
