### ISSUE TITLE
Suggestion: Seafood Platter

### ISSUE THREAD

**Issue by Aceplante** [Nyancatpig/Cultural-Delights-1.18.2#30]
Crafted with three cooked calamari, which as of now, is not used in any other recipes and has bad stats on its own. This would potentially fix that.

**Comment by Nyancatpig** [comment]
the 1.18 version of cultural delights is no longer supported, any new additions would go to the 1.19 version
as for this suggestion in particular, there is in fact a squid dish in the works (also there is already a calamari roll)
