### ISSUE TITLE
Cuttable pufferfish/tropical fish

### ISSUE THREAD

**Issue by Aceplante** [Nyancatpig/Cultural-Delights-1.18.2#36]
Just like cod and salmon in farmers delight, pufferfish and tropical fish should be cuttable too.

Pufferfish would give two "raw pufferfish slice" and 1 "poison sac"

Tropical fish would simply give 2 "raw tropical fish slice" (and sometimes a bonemeal?)

**Comment by Nyancatpig** [comment]
The 1.18 version of cultural delights is no longer supported, any new additions would go to the 1.19 version.

I suggest that you leave your issues on the 1.19 github page.
Also feature suggestions don't belong on the issue tracker anyway, please put them on the curseforge page or the discord.
