### ISSUE TITLE
Eggplant only drops 1 even with fortune

### ISSUE THREAD

**Issue by Aceplante** [Nyancatpig/Cultural-Delights-1.18.2#37]
Title. Even if this was intentional it seems odd. Maybe it and corn should drop 1-3?

**Comment by Nyancatpig** [comment]
This is now my third time telling you that this version of the mod has been discontinued.
Please stop leaving issues here.

**Comment by Aceplante** [comment]
uh okay? where is the new one. This is the page that the issue tab of your mod brings me to

Edit: would you prefer I used the regular cultural delights or specially the 1.19 one?
