### ISSUE TITLE
Missing Knife Tag

### ISSUE THREAD

**Issue by ObsyTek** [Nyancatpig/Cultural-Delights-1.18.2#38]
I'd like to cut some items like avocados or cucumber, but it doesn't work with any knife. When opening the recipe with JEI, it tells me to do it on the cutting board but there's a empty tag where it should tell what tool to use (i.e Knife)

Playing Minecraft 1.19.2 Forge

![missing tag](https://github.com/Nyancatpig/Cultural-Delights-1.18.2/assets/133168966/c9449472-b17d-4105-83de-e332927e39e2)

**Comment by Nyancatpig** [comment]
what other mods are you using?

one of them probably adds a knife that doesn't exist to the knifes tag, causing it not to work.

also this is the github page for the 1.18.2 version.
