### ISSUE TITLE
stripping avocado log bug? + incompatibility with immersive weathering stripping change

### ISSUE THREAD

**Issue by nicolhaq** [Nyancatpig/Cultural-Delights-1.18.2#4]
MC version : 1.18.2
Forge version: 40.1.22
culturaldelights-1.18.2-0.11.jar

stripping avocado log transform it in jungle log instead of stripped jungle log,
it also do not drop bark as it should with immersive weathering and stripped jungle log cannot be re barked as avocado log.

**Comment by Nyancatpig** [comment]
the avocado log no longer strips into a jungle log
if immersive weathering does not work with avocado logs, it may be an issue on their end, although i assume applying bark to stripped jungle logs would just turn them into jungle logs
