### ISSUE TITLE
Cultural Delights [Fabric] Avocado trees leaves do not decay when logs are broken 

### ISSUE THREAD

**Issue by dre3002** [Nyancatpig/Cultural-Delights-1.18.2#41]
Fabric/Mod version:

fabric-loader-0.14.22-1.20.1
cultural-delights-fabric-0.14.11+1.20.1

Bug:
After breaking the logs of an Avocado tree the leaves remain in place forever

Steps to reproduce:
Plant Avocado tree. Harvest logs.

Expected behaviour:
After breaking the logs of an Avocado tree, the leaves should naturally decay on their own.

**Comment by Nyancatpig** [comment]
Unfortunately this is the github page for the 1.18.2 forge version of cultural delights and thus I cannot help you
