### ISSUE TITLE
Corn doesn't grow when planted

### ISSUE THREAD

**Issue by Noirsette** [Nyancatpig/Cultural-Delights-1.18.2#42]
In my quest to cultivate as many plants as I can I noticed that the corn doesn't grow when planted. I'm using the mod as part of the Better MC Fabric modpack but after bring up the issue there I was old to bring up the issue to the official mod as if the modpack is fully updated then there is no issues on their part. Any help would be appreciated!

**Comment by Nyancatpig** [comment]
This is the github for the forge version, there's a separate mod page for the fabric version.
Good luck getting the issue fixed though, the fabric version has a lot of known bugs that haven't been fixed.
